language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - mvn -T 2C clean package -DskipTests=true
  - cd production-component/common-util; mvn install; cd -

after_success:
  - mvn -T 2C clean site

#branches:
#  only:
#    - test
notifications:
  email: true
